version: '3.8'
services: 
    web:
        # overriding Dockerfile selection
        build: 
            # look at the current directory
            context: .
            # find the Dockerfile
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: true